### ISSUE TITLE
Class 'BaconQrCode\Renderer\Image\Png' not found

### ISSUE THREAD

**Issue by brvnks** [antonioribeiro/google2fa-laravel#34] opened 2018-05-25 20:17 UTC
Hello, i'm following this tutorial and when i'm going to register the client in my newsboard app, this error always appear.

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'BaconQrCode\Renderer\Image\Png' not found

 public function getQRCodeInline($company, $holder, $secret, $size = 200, $encoding = 'utf-8')
    {
        $url = $this->getQRCodeUrl($company, $holder, $secret);
 
        $renderer = new Png();
        $renderer->setWidth($size);
        $renderer->setHeight($size);
 
        $bacon = new BaconQrCodeWriter($renderer);
        $data = $bacon->writeString($url, $encoding);
 
        return 'data:image/png;base64,'.base64_encode($data);
    }

can you help me with that?
remembering that your bacon package is already installed, and i did it again, revert on gitkraken and did it again all the packages and its not working :(

**Comment by evannamonpinion** [comment] 2018-07-13 02:07
did you try using this ? 
composer require bacon/bacon-qr-code 1.0.3

source: https://github.com/cwt137/google-laravel-2fa/issues/2

i just followed this one and fixed the error, try deleting the vendor folder and re install baconQr with this one

**Comment by candro** [comment] 2018-07-15 19:37
`@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif`

**Comment by sergiq** [comment] 2018-10-25 13:49
The problems comes from the version of the bacon/bacon-qr-code. This pack is not compatible with the last-stable version of bacon/bacon-qr-code (^2.0.0). This lib should requires the library in a certain revision range (^1.0.0).

**Comment by sergiq** [comment] 2018-10-25 14:11
Duplicate of #32

**Closed** 2019-03-21 22:27 UTC
