### ISSUE TITLE
error on laravel v6.12.0

### ISSUE THREAD

**Issue by it-can** [antonioribeiro/google2fa-laravel#93] opened 2020-01-23 08:22 UTC
Getting now this error on Laravel 6.12.0 (also on 6.11.0)

PHP 7.4.2 (cli) (built: Jan 22 2020 06:30:58) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

There seems to be no problem on php 7.3..

```
Symfony\Component\Debug\Exception\FatalErrorException  : Access level to PragmaRX\Google2FALaravel\Support\Config::config() must be public (as in class PragmaRX\Google2FALaravel\Support\Auth)
```

**Comment by it-can** [comment] 2020-01-23 09:08
@antonioribeiro can you take a look at this? and PR #94  ?

**Comment by njaremko** [comment] 2020-01-23 22:07
This is caused by PHP 7.4.2 (works fine in 7.4.1), but the fix works.

**Comment by antonioribeiro** [comment] 2020-01-26 00:41
Sorry, what? We need a `public` method, on an internal class, used as dependency of only one other class, to be made `protected` in order to fix a problem introduced on a PHP patch version? Shouldn't that be reported to PHP Internals? :trollface:

**Comment by antonioribeiro** [comment] 2020-01-26 00:48
Merged. Thank you!!

**Closed by antonioribeiro** 2020-01-26 00:48 UTC
