### ISSUE TITLE
Compatibility between 0.2.0 and 0.2.1 with a newer version of the base

### ISSUE THREAD

**Issue by devsi** [antonioribeiro/google2fa-laravel#51] opened 2019-03-21 00:17 UTC
By changing the `pragmarx/google2fa-laravel` composer.json of `pragmarx/google2fa` from  `~3.0` to `~4.0` you have introduced a major breaking change in to a minor version of the package.

Removal of `getQRCodeInline()` function in `4.0` is a compatibility breaking change, and although nothing major changed in `google2fa-laravel`, the result of changing the core package has a direct major knock-on effect. 

We just had our 2FA generation go down because the minor update of the Laravel package is the accepted criteria. 

Can you consider re-releasing v0.2.1 as v0.3.0 instead seeing as v3.0 - v4.0 is the real change here?

**Comment by TheFrankman** [comment] 2019-03-21 17:16
I have run into this issue as well!!!!
Was a serious issue, luckily a downgrade is an easy fix however you wouldn't expect this!
Our composer was set to : `"pragmarx/google2fa-laravel": "^0.2.0"` allowing only for the last point upgrade, this should be relatively safe!

Anyone else hitting this issue i recommend setting your composer versioning like this : 

```
"pragmarx/google2fa-laravel": "v0.2.0",
"pragmarx/google2fa": "v3.0.3",
```

**Comment by devsi** [comment] 2019-03-21 17:24
If you've taken out the `^`, you should only need to specify 0.2.0, then run composer upgrade. It'll automatically downgrade `google2fa` and be back in a working state. That way you don't also lock google2fa. Same outcome as your solution though!

**Comment by antonioribeiro** [comment] 2019-03-21 19:25
Sorry all those changes are because the Google API that generated the QRCode was taken down by Google. So we already had a breaking change anyway.

As you can see in https://github.com/antonioribeiro/google2fa/issues/107, the only option to fix this breaking change was to add Bacon QRCode to the list of requirements of the Google2FA package.

To fix it users must upgrade do Google2FA Laravel 0.3.0 (Google2FA 5.0.0) and start using a something else to generate QRCodes. We have some options [here](https://github.com/antonioribeiro/google2fa#qr-code-packages)

`getQRCodeInline()` was using BaconQRCode, which was removed in G2FA 4.0.

One thing we could do is to change Google2FA-Laravel to use [Google2FA-QRCode](https://github.com/antonioribeiro/google2fa-qrcode), which uses Bacon 2.0 and still contains a `getQRCodeInline()` method.

**Comment by devsi** [comment] 2019-03-21 21:59
Has the QRCode library been taken down by Google already? We downgraded to Google2FA Laravel `0.2.0` and the barcodes are still working.

If it's completely removed by Google then I guess even a minor version change cannot be helped. I think it's a good idea to use Bacon 2.0 so we don't lose `getQRCodeInline()`. That way `0.2.1` would remain compatible and not have a major break due to being on `~4.0`

**Comment by antonioribeiro** [comment] 2019-03-21 22:02
It was down yesterday, yes, but getQRCodeInline uses BaconQRCode, which was removed from Google2FA, and, thus, newer versions of Google2FA-Laravel.

**Comment by antonioribeiro** [comment] 2019-03-21 22:05
> EDIT: I can look in to this and create a Pull Request if you're busy working on other things!

Are you able to test master? I'm moving to use Google2FA QRCode as base class for Google2FA Laravel, which will bring `getQRCodeInline()` back

**Comment by antonioribeiro** [comment] 2019-03-21 23:30
Just tagged 1.0.0, now using Google2FA QRCode to keep supporting QRCode generation.

**Comment by devsi** [comment] 2019-03-21 23:48
Hi sorry that was an immediate thing! I can definitely help out when I have a free moment. :) Had a bit of a meltdown situation at work so never got time to crack on with it!

**Comment by TheFrankman** [comment] 2019-03-22 10:07
V1.0.1 is all good for my Laravel 5.7 project but not my 5.4 project.
However the following still seems to work for the 5.4 project : 

```
"pragmarx/google2fa-laravel": "v0.2.0",
"pragmarx/google2fa": "v3.0.3",
```

**Comment by antonioribeiro** [comment] 2019-03-22 19:55
> However the following still seems to work for the 5.4 project :

@TheFrankman, just tagged 1.0.1, which should allow Laravel 5.4. Would you test on your app, please?

**Comment by TheFrankman** [comment] 2019-03-22 20:10
Will do tomorrow

**Comment by TheFrankman** [comment] 2019-03-25 14:38
@antonioribeiro - I can confirm that this works on my laravel 5.4 project.

**Comment by antonioribeiro** [comment] 2019-03-25 14:39
@TheFrankman, thank you!

**Closed by antonioribeiro** 2019-03-25 14:39 UTC
